const PlayerList = {
  team1: [
    {
      id: 1,
      playerName: "srinath",
      jessyNumber: 26,
      role: "Bat",
      isPlaying: false,
      runs: null,
      wickets: null,
      team: 1,
    },
    {
      id: 2,
      playerName: "notSrinath",
      jessyNumber: 15,
      role: "Bat",
      isPlaying: false,
      runs: null,
      wickets: null,
      team: 1,
    },
    {
      id: 3,
      playerName: "TonyStark",
      jessyNumber: 17,
      role: "Bowl",
      isPlaying: false,
      runs: null,
      wickets: null,
      team: 1,
    },
    {
      id: 4,
      playerName: "Dhoni",
      jessyNumber: 7,
      role: "Bat",
      isPlaying: false,
      runs: null,
      wickets: null,
      team: 1,
    },
  ],
  team2: [
    {
      id: 1,
      playerName: "srinath2",
      jessyNumber: 26,
      role: "Bat",
      isPlaying: false,
      runs: null,
      wickets: null,
      team: 2,
    },
    {
      id: 2,
      playerName: "notSrinathTeam2",
      jessyNumber: 15,
      role: "Bat",
      isPlaying: false,
      runs: null,
      wickets: null,
      team: 2,
    },
    {
      id: 3,
      playerName: "TonyStarkTeam2",
      jessyNumber: 17,
      role: "Bowl",
      isPlaying: false,
      runs: null,
      wickets: null,
      team: 2,
    },
  ],
};

export default PlayerList;
